# makefiles := $(shell ls *.mk)

# all::
# 	@ for i in $(makefiles); \
# 	do \
# 		make -k -f $$i; \
# 	done;


#include analyzer.mk

my_name = analyzer
my_dir  = $(src_top_dir)/$(my_name)

include ../common.mk

core_obj = UserParamMan.o HodoParamMan.o HodoPHCMan.o DCGeomMan.o DCTdcCalibMan.o DCDriftParamMan.o DCGeomRecord.o ConfMan.o

my_obj_skeleton := $(core_obj) user_skeleton.o
my_tgt_skeleton := $(bin_dir)/skeleton

my_obj_rawhist_e13  := $(core_obj) user_rawhist_e13.o HistMaker.o GuiPs.o PsMaker.o MacroBuilder.o
my_tgt_rawhist_e13  := $(bin_dir)/raw_hist_e13

my_obj_pwo  := $(core_obj) user_pwo.o HistMaker.o MacroBuilder.o
my_tgt_pwo  := $(bin_dir)/pwo_hist

all:: $(my_tgt_skeleton) $(my_tgt_rawhist_e13) $(my_tgt_pwo)

 $(my_dir)/dict/GuiPs_Dict.cc: \
 $(my_dir)/include/GuiPs.hh \
 $(my_dir)/linkdef/GuiPs_LinkDef.hh
	$(QUIET) $(ECHO) "=== Generating dictionary $^ - > $@"
	rootcint -f $@ -c -p $^

 $(my_dir)/dict/HistMaker_Dict.cc: \
 $(my_dir)/include/HistMaker.hh \
 $(my_dir)/linkdef/HistMaker_LinkDef.hh
	$(QUIET) $(ECHO) "=== Generating dictionary $^ - > $@"
	rootcint -f $@ -c -p $^
#_____________________________________________________________________________
my_obj_skeleton := $(addprefix $(my_dir)/src/,$(my_obj_skeleton))
my_lib_skeleton := libmyskeleton.so
$(eval $(call make-lib,$(my_lib_skeleton),$(my_obj_skeleton)))
$(eval $(call make-gui-target,$(my_tgt_skeleton),$(my_lib_skeleton)))

#_____________________________________________________________________________
my_obj_rawhist_e13 := $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e13))
my_obj_rawhist_e13 := $(my_obj_rawhist_e13) \
		  $(my_dir)/dict/HistMaker_Dict.o \
		  $(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e13 := libmyrawhist_e13.so
$(eval $(call make-lib,$(my_lib_rawhist_e13),$(my_obj_rawhist_e13)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e13),$(my_lib_rawhist_e13)))

#_____________________________________________________________________________
my_obj_pwo := $(addprefix $(my_dir)/src/,$(my_obj_pwo))
my_obj_pwo := $(my_obj_pwo) \
	      $(my_dir)/dict/HistMaker_Dict.o
my_lib_pwo := libmypwo.so
$(eval $(call make-lib,$(my_lib_pwo),$(my_obj_pwo)))
$(eval $(call make-gui-target,$(my_tgt_pwo),$(my_lib_pwo)))
