# makefiles := $(shell ls *.mk)

# all::
# 	@ for i in $(makefiles); \
# 	do \
# 		$(MAKE) -k -f $$i; \
# 	done;


#include analyzer.mk

my_name = analyzer
my_dir  = $(src_top_dir)/$(my_name)

include ../common.mk

#_______________________________________________________________________________
core_src	:= $(wildcard $(my_dir)/src/*.cc)
core_src	:= $(filter-out $(my_dir)/src/user_%.cc,$(core_src))
core_src	:= $(filter-out $(my_dir)/src/GuiPs.cc,$(core_src))
core_src	:= $(filter-out $(my_dir)/src/PsMaker.cc,$(core_src))

core_heads	:= $(wildcard $(my_dir)/include/*.hh)
core_heads	:= $(filter-out $(my_dir)/include/GuiPs.hh,$(core_heads))
core_heads	:= $(filter-out $(my_dir)/include/PsMaker.hh,$(core_heads))

core_obj	:= $(core_src:$(my_dir)/src/%.cc=%.o)

gui_src		+= $(my_dir)/src/GuiPs.cc
gui_src		+= $(my_dir)/src/PsMaker.cc
gui_obj		:= $(gui_src:$(my_dir)/src/%.cc=%.o)

user_src	+= $(filter $(my_dir)/src/user_%.cc,$(wildcard $(my_dir)/src/*.cc))
user_obj	:= $(user_src:$(my_dir)/src/%.cc=%.o)

#_______________________________________________________________________________
core_linkdef	= $(my_dir)/linkdef/K18AnalyzerCore_LinkDef.hh
core_dict_src	= $(core_linkdef:$(my_dir)/linkdef/%LinkDef.hh=$(my_dir)/dict/%Dict.cc)
core_dict_obj	= $(core_dict_src:%.cc=%.o)
core_dict_pcm	= $(core_dict_src:%.cc=%_rdict.pcm)
core_dict_lib	= $(core_dict_pcm:$(my_dir)/dict/%=$(lib_dir)/%)
core_lib	= $(core_dict_src:$(my_dir)/dict/%_Dict.cc=$(lib_dir)/lib%.so)

#_______________________________________________________________________________
my_obj_skeleton	:= $(core_obj) user_skeleton.o
my_tgt_skeleton	:= $(bin_dir)/skeleton

my_obj_udebug	:= $(core_obj) user_unpacker_debug.o
my_tgt_udebug	:= $(bin_dir)/unpacker_debug

my_obj_tag	:= $(core_obj) user_tag_checker.o
my_tgt_tag	:= $(bin_dir)/tag_checker

my_obj_event_display	:= $(core_obj) user_event_display.o
my_tgt_event_display	:= $(bin_dir)/event_display

my_obj_rawhist_e13	:= $(core_obj) user_rawhist_e13.o $(gui_obj)
my_tgt_rawhist_e13	:= $(bin_dir)/raw_hist_e13

my_obj_rawhist_e0705	:= $(core_obj) user_rawhist_e0705.o $(gui_obj)
my_tgt_rawhist_e0705	:= $(bin_dir)/raw_hist_e0705

my_obj_rawhist_e07	:= $(core_obj) user_rawhist_e07.o $(gui_obj)
my_tgt_rawhist_e07	:= $(bin_dir)/raw_hist_e07

my_obj_rawhist_e40	:= $(core_obj) user_rawhist_e40.o $(gui_obj)
my_tgt_rawhist_e40	:= $(bin_dir)/raw_hist_e40

my_obj_rawhist_catch	:= $(core_obj) user_rawhist_catch.o $(gui_obj)
my_tgt_rawhist_catch	:= $(bin_dir)/raw_hist_catch

my_obj_rawhist_e03	:= $(core_obj) user_rawhist_e03.o $(gui_obj)
my_tgt_rawhist_e03	:= $(bin_dir)/raw_hist_e03

my_obj_rawhist_e42	:= $(core_obj) user_rawhist_e42.o $(gui_obj)
my_tgt_rawhist_e42	:= $(bin_dir)/raw_hist_e42

my_obj_rawhist_e42_woTPC	:= $(core_obj) user_rawhist_e42_woTPC.o $(gui_obj)
my_tgt_rawhist_e42_woTPC	:= $(bin_dir)/raw_hist_e42_woTPC

my_obj_rawhist_e70	:= $(core_obj) user_rawhist_e70.o $(gui_obj)
my_tgt_rawhist_e70	:= $(bin_dir)/raw_hist_e70

my_obj_rawhist_hbx	:= $(core_obj) user_rawhist_hbx.o $(gui_obj)
my_tgt_rawhist_hbx	:= $(bin_dir)/raw_hist_hbx

my_obj_rawhist_vmeeasiroc	:= $(core_obj) user_rawhist_vmeeasiroc.o $(gui_obj)
my_tgt_rawhist_vmeeasiroc	:= $(bin_dir)/raw_hist_vmeeasiroc

my_obj_mstmonitor_e40	:= $(core_obj) user_mstmonitor_e40.o
my_tgt_mstmonitor_e40	:= $(bin_dir)/mstmonitor_e40

my_obj_mstmonitorjs_e40	:= $(core_obj) user_mstmonitorjs_e40.o
my_tgt_mstmonitorjs_e40	:= $(bin_dir)/mstmonitorjs_e40

my_obj_vme01debug	:= $(core_obj) user_vme01debug.o
my_tgt_vme01debug	:= $(bin_dir)/raw_vme01debug

my_obj_jsroot_e07	:= $(core_obj) user_jsroot_e07.o
my_tgt_jsroot_e07	:= $(bin_dir)/jsroot_e07

my_obj_jsroot_e40	:= $(core_obj) user_jsroot_e40.o
my_tgt_jsroot_e40	:= $(bin_dir)/jsroot_e40

my_obj_jsroot_e03	:= $(core_obj) user_jsroot_e03.o
my_tgt_jsroot_e03	:= $(bin_dir)/jsroot_e03

my_obj_jsroot_e42	:= $(core_obj) user_jsroot_e42.o
my_tgt_jsroot_e42	:= $(bin_dir)/jsroot_e42

my_obj_jsroot_scaler	:= $(core_obj) user_jsroot_scaler.o
my_tgt_jsroot_scaler	:= $(bin_dir)/jsroot_scaler

my_obj_jsroot_scaler_hbx	:= $(core_obj) user_jsroot_scaler_hbx.o
my_tgt_jsroot_scaler_hbx	:= $(bin_dir)/jsroot_scaler_hbx

my_obj_jsroot_beammonitor	:= $(core_obj) user_jsroot_beammonitor.o
my_tgt_jsroot_beammonitor	:= $(bin_dir)/jsroot_beammonitor

my_obj_jsroot_beamprofile	:= $(core_obj) user_jsroot_beamprofile.o
my_tgt_jsroot_beamprofile	:= $(bin_dir)/jsroot_beamprofile

my_obj_jsroot_totmonitor	:= $(core_obj) user_jsroot_totmonitor.o
my_tgt_jsroot_totmonitor	:= $(bin_dir)/jsroot_totmonitor

my_obj_emc_position	:= $(core_obj) user_emc_position.o
my_tgt_emc_position	:= $(bin_dir)/emc_position

my_obj_beammonitor	:= $(core_obj) user_beammonitor.o
my_tgt_beammonitor	:= $(bin_dir)/beammonitor

my_obj_beamprofile_e13  := $(core_obj) user_beamprofile_e13.o
my_tgt_beamprofile_e13  := $(bin_dir)/beamprofile_e13

my_obj_beamprofile_e07  := $(core_obj) user_beamprofile_e07.o
my_tgt_beamprofile_e07  := $(bin_dir)/beamprofile_e07

my_obj_beamprofile_e05  := $(core_obj) user_beamprofile_e05.o
my_tgt_beamprofile_e05  := $(bin_dir)/beamprofile_e05

my_obj_beamprofile_e03  := $(core_obj) user_beamprofile_e03.o
my_tgt_beamprofile_e03  := $(bin_dir)/beamprofile_e03

my_obj_beamprofile_e40  := $(core_obj) user_beamprofile_e40.o
my_tgt_beamprofile_e40  := $(bin_dir)/beamprofile_e40

my_obj_beamprofile_e42  := $(core_obj) user_beamprofile_e42.o
my_tgt_beamprofile_e42  := $(bin_dir)/beamprofile_e42

my_obj_emc_ssd_monitor	:= $(core_obj) user_emc_ssd_monitor.o
my_tgt_emc_ssd_monitor	:= $(bin_dir)/emc_ssd_monitor

my_obj_scaler_e13	:= $(core_obj) user_scaler_e13.o
my_tgt_scaler_e13	:= $(bin_dir)/scaler_e13

my_obj_scaler_e0705	:= $(core_obj) user_scaler_e0705.o
my_tgt_scaler_e0705	:= $(bin_dir)/scaler_e0705

my_obj_scaler_e07	:= $(core_obj) user_scaler_e07.o
my_tgt_scaler_e07	:= $(bin_dir)/scaler_e07

my_obj_scaler_e40	:= $(core_obj) user_scaler_e40.o
my_tgt_scaler_e40	:= $(bin_dir)/scaler_e40

my_obj_scaler_e03	:= $(core_obj) user_scaler_e03.o
my_tgt_scaler_e03	:= $(bin_dir)/scaler_e03

my_obj_scaler_e42	:= $(core_obj) user_scaler_e42.o
my_tgt_scaler_e42	:= $(bin_dir)/scaler_e42

my_obj_scaler_sch	:= $(core_obj) user_scaler_sch.o
my_tgt_scaler_sch	:= $(bin_dir)/scaler_sch

my_obj_scaler_daq	:= $(core_obj) user_scaler_daq.o
my_tgt_scaler_daq	:= $(bin_dir)/scaler_daq

my_obj_hbjscaler	:= $(core_obj) user_hbjscaler_ana.o
my_tgt_hbjscaler	:= $(bin_dir)/HBJscalerAna

my_obj_hbj_ana	:= $(core_obj) user_hbj_ana.o $(gui_obj)
my_tgt_hbj_ana	:= $(bin_dir)/hbj_ana

my_obj_pwo	:= $(core_obj) user_pwo.o
my_tgt_pwo	:= $(bin_dir)/pwo_hist

my_obj_ktune_y2020      := $(core_obj) user_ktune_y2020.o $(gui_obj)
my_tgt_ktune_y2020      := $(bin_dir)/ktune_y2020



#_______________________________________________________________________________
all::	$(my_tgt_skeleton) $(my_tgt_udebug) $(my_tgt_tag) \
	$(my_tgt_event_display) \
	$(my_tgt_rawhist_e42) \
	$(my_tgt_rawhist_e42_woTPC) \
	$(my_tgt_rawhist_e70) \
	$(my_tgt_rawhist_hbx) \
	$(my_tgt_rawhist_vmeeasiroc) \
	$(my_tgt_beammonitor) \
	$(my_tgt_scaler_e42) \
	$(my_tgt_scaler_sch) \
	$(my_tgt_scaler_daq) \
	$(my_tgt_jsroot_beamprofile) \
	$(my_tgt_jsroot_e42) \
	$(my_tgt_jsroot_scaler) \
	$(my_tgt_jsroot_scaler_hbx) \
	$(my_tgt_jsroot_beammonitor) \
	$(my_tgt_jsroot_totmonitor) \
	$(my_tgt_vme01debug) \
	$(my_tgt_ktune_y2020) \
	$(core_dict_lib)
#	$(my_old_tgt)

my_old_tgt	:= $(my_tgt_rawhist_e13) $(my_tgt_beamprofile_e13) \
	$(my_tgt_rawhist_e40) \	$(my_tgt_jsroot_e40) \
	$(my_tgt_scaler_e13) $(my_tgt_hbjscaler) \
	$(my_tgt_hbj_ana) $(my_tgt_pwo) \
	$(my_tgt_rawhist_e0705) $(my_tgt_scaler_e0705) \
	$(my_tgt_rawhist_e07) \
	$(my_tgt_emc_position) \
	$(my_tgt_emc_ssd_monitor) \
	$(my_tgt_scaler_e07) \
	$(my_tgt_jsroot_e07) \
	$(my_tgt_beamprofile_e07) \
	$(my_tgt_beamprofile_e42) \
        $(my_tgt_mstmonitor_e40) \
	$(my_tgt_rawhist_catch) \
	$(my_tgt_scaler_e40) \
	$(my_tgt_beamprofile_e40) \
        $(my_tgt_mstmonitorjs_e40) \
	$(my_tgt_rawhist_e03) \
	$(my_tgt_beamprofile_e03) \
	$(my_tgt_scaler_e03) \
	$(my_tgt_jsroot_e03)

#_______________________________________________________________________________
$(my_dir)/dict/%_Dict.cc: $(my_dir)/include/%.hh $(my_dir)/linkdef/%_LinkDef.hh
	$(QUIET) $(ECHO) "$(blue)=== Generating dictionary $^ - > $@$(default_color)"
	$(rootcint) -f $@ $(CXXFLAGS) $^
	$(QUIET) if [ -f $(subst .cc,_rdict.pcm,$@) ]; then \
	$(CP) $(subst .cc,_rdict.pcm,$@) $(lib_dir); fi

#_______________________________________________________________________________
$(core_dict_src): $(core_heads) $(core_linkdef)
	$(QUIET) $(ECHO) "$(blue)=== Generating dictionary $^ - > $@$(default_color)"
	$(rootcint) -f $@ $(CXXFLAGS) $^

$(core_dict_lib): $(core_dict_pcm) $(core_dict_src)
	$(QUIET) $(CP) $< $@

$(core_lib): $(addprefix $(my_dir)/src/,$(core_obj)) $(core_dict_obj)
	$(QUIET) $(ECHO) "$(yellow)=== Generating shared object $^ - > $@$(default_color)"
	$(CXX) $(SOFLAGS) $^ -o $@

#_______________________________________________________________________________
my_obj_skeleton	:= $(addprefix $(my_dir)/src/,$(my_obj_skeleton))
my_lib_skeleton	:= libmyskeleton.so
$(eval $(call make-lib,$(my_lib_skeleton),$(my_obj_skeleton)))
$(eval $(call make-gui-target,$(my_tgt_skeleton),$(my_lib_skeleton)))

#_______________________________________________________________________________
my_obj_udebug	:= $(addprefix $(my_dir)/src/,$(my_obj_udebug))
my_lib_udebug	:= libmyudebug.so
$(eval $(call make-lib,$(my_lib_udebug),$(my_obj_udebug)))
$(eval $(call make-nogui-target,$(my_tgt_udebug),$(my_lib_udebug)))

#_______________________________________________________________________________
my_obj_tag	:= $(addprefix $(my_dir)/src/,$(my_obj_tag))
my_lib_tag	:= libmytag.so
$(eval $(call make-lib,$(my_lib_tag),$(my_obj_tag)))
$(eval $(call make-nogui-target,$(my_tgt_tag),$(my_lib_tag)))

#_______________________________________________________________________________
my_obj_event_display	:= $(addprefix $(my_dir)/src/,$(my_obj_event_display))
my_lib_event_display	:= libmyevent_display.so
$(eval $(call make-lib,$(my_lib_event_display),$(my_obj_event_display)))
$(eval $(call make-nogui-target,$(my_tgt_event_display),$(my_lib_event_display)))

#_______________________________________________________________________________
my_obj_rawhist_e13	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e13))
my_obj_rawhist_e13	:= $(my_obj_rawhist_e13) \
		  $(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e13 := libmyrawhist_e13.so
$(eval $(call make-lib,$(my_lib_rawhist_e13),$(my_obj_rawhist_e13)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e13),$(my_lib_rawhist_e13)))

#_______________________________________________________________________________
my_obj_rawhist_e0705	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e0705))
my_obj_rawhist_e0705	:= $(my_obj_rawhist_e0705) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e0705	:= libmyrawhist_e0705.so
$(eval $(call make-lib,$(my_lib_rawhist_e0705),$(my_obj_rawhist_e0705)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e0705),$(my_lib_rawhist_e0705)))

#_______________________________________________________________________________
my_obj_rawhist_e07	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e07))
my_obj_rawhist_e07	:= $(my_obj_rawhist_e07) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e07	:= libmyrawhist_e07.so
$(eval $(call make-lib,$(my_lib_rawhist_e07),$(my_obj_rawhist_e07)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e07),$(my_lib_rawhist_e07)))

#_______________________________________________________________________________
my_obj_rawhist_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e40))
my_obj_rawhist_e40	:= $(my_obj_rawhist_e40) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e40	:= libmyrawhist_e40.so
$(eval $(call make-lib,$(my_lib_rawhist_e40),$(my_obj_rawhist_e40)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e40),$(my_lib_rawhist_e40)))

#_______________________________________________________________________________
my_obj_rawhist_catch	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_catch))
my_obj_rawhist_catch	:= $(my_obj_rawhist_catch) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_catch	:= libmyrawhist_catch.so
$(eval $(call make-lib,$(my_lib_rawhist_catch),$(my_obj_rawhist_catch)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_catch),$(my_lib_rawhist_catch)))
#

#_______________________________________________________________________________
my_obj_rawhist_e03	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e03))
my_obj_rawhist_e03	:= $(my_obj_rawhist_e03) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e03	:= libmyrawhist_e03.so
$(eval $(call make-lib,$(my_lib_rawhist_e03),$(my_obj_rawhist_e03)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e03),$(my_lib_rawhist_e03)))

#_______________________________________________________________________________
my_obj_rawhist_e42	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e42))
my_obj_rawhist_e42	:= $(my_obj_rawhist_e42) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e42	:= libmyrawhist_e42.so
$(eval $(call make-lib,$(my_lib_rawhist_e42),$(my_obj_rawhist_e42)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e42),$(my_lib_rawhist_e42)))

#_______________________________________________________________________________
my_obj_rawhist_e42_woTPC	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e42_woTPC))
my_obj_rawhist_e42_woTPC	:= $(my_obj_rawhist_e42_woTPC) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e42_woTPC	:= libmyrawhist_e42_woTPC.so
$(eval $(call make-lib,$(my_lib_rawhist_e42_woTPC),$(my_obj_rawhist_e42_woTPC)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e42_woTPC),$(my_lib_rawhist_e42_woTPC)))

#______________________________________________________________________________
my_obj_rawhist_e70	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_e70))
my_obj_rawhist_e70	:= $(my_obj_rawhist_e70) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_e70	:= libmyrawhist_e70.so
$(eval $(call make-lib,$(my_lib_rawhist_e70),$(my_obj_rawhist_e70)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_e70),$(my_lib_rawhist_e70)))

#_______________________________________________________________________________

my_obj_rawhist_hbx	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_hbx))
my_obj_rawhist_hbx	:= $(my_obj_rawhist_hbx) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_hbx	:= libmyrawhist_hbx.so
$(eval $(call make-lib,$(my_lib_rawhist_hbx),$(my_obj_rawhist_hbx)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_hbx),$(my_lib_rawhist_hbx)))

#_______________________________________________________________________________
my_obj_rawhist_vmeeasiroc	:= $(addprefix $(my_dir)/src/,$(my_obj_rawhist_vmeeasiroc))
my_obj_rawhist_vmeeasiroc	:= $(my_obj_rawhist_vmeeasiroc) \
		$(my_dir)/dict/GuiPs_Dict.o
my_lib_rawhist_vmeeasiroc	:= libmyrawhist_vmeeasiroc.so
$(eval $(call make-lib,$(my_lib_rawhist_vmeeasiroc),$(my_obj_rawhist_vmeeasiroc)))
$(eval $(call make-gui-target,$(my_tgt_rawhist_vmeeasiroc),$(my_lib_rawhist_vmeeasiroc)))
#
#_______________________________________________________________________________
my_obj_vme01debug	:= $(addprefix $(my_dir)/src/,$(my_obj_vme01debug))
my_lib_vme01debug	:= libmyvme01debug.so
$(eval $(call make-lib,$(my_lib_vme01debug),$(my_obj_vme01debug)))
$(eval $(call make-gui-target,$(my_tgt_vme01debug),$(my_lib_vme01debug)))
#
#_______________________________________________________________________________
my_obj_mstmonitor_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_mstmonitor_e40))
my_lib_mstmonitor_e40	:= libmymstmonitor_e40.so
$(eval $(call make-lib,$(my_lib_mstmonitor_e40),$(my_obj_mstmonitor_e40)))
$(eval $(call make-nogui-target,$(my_tgt_mstmonitor_e40),$(my_lib_mstmonitor_e40)))
#
#_______________________________________________________________________________
my_obj_mstmonitorjs_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_mstmonitorjs_e40))
my_obj_mstmonitorjs_e40	:= $(my_obj_mstmonitorjs_e40)
my_lib_mstmonitorjs_e40	:= libmymstmonitorjs_e40.so
$(eval $(call make-lib,$(my_lib_mstmonitorjs_e40),$(my_obj_mstmonitorjs_e40)))
$(eval $(call make-nogui-target,$(my_tgt_mstmonitorjs_e40),$(my_lib_mstmonitorjs_e40)))
#
#_______________________________________________________________________________
my_obj_jsroot_e07	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_e07))
my_obj_jsroot_e07	:= $(my_obj_jsroot_e07)
my_lib_jsroot_e07	:= libmyjsroot_e07.so
$(eval $(call make-lib,$(my_lib_jsroot_e07),$(my_obj_jsroot_e07)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_e07),$(my_lib_jsroot_e07)))
#
#_______________________________________________________________________________
my_obj_jsroot_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_e40))
my_obj_jsroot_e40	:= $(my_obj_jsroot_e40)
my_lib_jsroot_e40	:= libmyjsroot_e40.so
$(eval $(call make-lib,$(my_lib_jsroot_e40),$(my_obj_jsroot_e40)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_e40),$(my_lib_jsroot_e40)))
#
#_______________________________________________________________________________
my_obj_jsroot_e03	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_e03))
my_obj_jsroot_e03	:= $(my_obj_jsroot_e03)
my_lib_jsroot_e03	:= libmyjsroot_e03.so
$(eval $(call make-lib,$(my_lib_jsroot_e03),$(my_obj_jsroot_e03)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_e03),$(my_lib_jsroot_e03)))
#
#_______________________________________________________________________________
my_obj_jsroot_e42	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_e42))
my_obj_jsroot_e42	:= $(my_obj_jsroot_e42)
my_lib_jsroot_e42	:= libmyjsroot_e42.so
$(eval $(call make-lib,$(my_lib_jsroot_e42),$(my_obj_jsroot_e42)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_e42),$(my_lib_jsroot_e42)))
#
#_______________________________________________________________________________
my_obj_jsroot_scaler	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_scaler))
my_obj_jsroot_scaler	:= $(my_obj_jsroot_scaler)
my_lib_jsroot_scaler	:= libmyjsroot_scaler.so
$(eval $(call make-lib,$(my_lib_jsroot_scaler),$(my_obj_jsroot_scaler)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_scaler),$(my_lib_jsroot_scaler)))
#
#_______________________________________________________________________________
my_obj_jsroot_scaler_hbx	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_scaler_hbx))
my_obj_jsroot_scaler_hbx	:= $(my_obj_jsroot_scaler_hbx)
my_lib_jsroot_scaler_hbx	:= libmyjsroot_scaler_hbx.so
$(eval $(call make-lib,$(my_lib_jsroot_scaler_hbx),$(my_obj_jsroot_scaler_hbx)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_scaler_hbx),$(my_lib_jsroot_scaler_hbx)))
#
#_______________________________________________________________________________
my_obj_jsroot_beammonitor	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_beammonitor))
my_obj_jsroot_beammonitor	:= $(my_obj_jsroot_beammonitor)
my_lib_jsroot_beammonitor	:= libmyjsroot_beammonitor.so
$(eval $(call make-lib,$(my_lib_jsroot_beammonitor),$(my_obj_jsroot_beammonitor)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_beammonitor),$(my_lib_jsroot_beammonitor)))
#
#_______________________________________________________________________________
my_obj_jsroot_beamprofile	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_beamprofile))
my_obj_jsroot_beamprofile	:= $(my_obj_jsroot_beamprofile)
my_lib_jsroot_beamprofile	:= libmyjsroot_beamprofile.so
$(eval $(call make-lib,$(my_lib_jsroot_beamprofile),$(my_obj_jsroot_beamprofile)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_beamprofile),$(my_lib_jsroot_beamprofile)))
#
#_______________________________________________________________________________
my_obj_jsroot_totmonitor	:= $(addprefix $(my_dir)/src/,$(my_obj_jsroot_totmonitor))
my_obj_jsroot_totmonitor	:= $(my_obj_jsroot_totmonitor)
my_lib_jsroot_totmonitor	:= libmyjsroot_totmonitor.so
$(eval $(call make-lib,$(my_lib_jsroot_totmonitor),$(my_obj_jsroot_totmonitor)))
$(eval $(call make-nogui-target,$(my_tgt_jsroot_totmonitor),$(my_lib_jsroot_totmonitor)))
#
#_______________________________________________________________________________
my_obj_emc_position := $(addprefix $(my_dir)/src/,$(my_obj_emc_position))
my_obj_emc_position := $(my_obj_emc_position)
my_lib_emc_position := libmyemc_position.so
$(eval $(call make-lib,$(my_lib_emc_position),$(my_obj_emc_position)))
$(eval $(call make-gui-target,$(my_tgt_emc_position),$(my_lib_emc_position)))

#_______________________________________________________________________________
my_obj_beammonitor := $(addprefix $(my_dir)/src/,$(my_obj_beammonitor))
my_lib_beammonitor := libmybeammonitor.so
$(eval $(call make-lib,$(my_lib_beammonitor),$(my_obj_beammonitor)))
$(eval $(call make-gui-target,$(my_tgt_beammonitor),$(my_lib_beammonitor)))

#_______________________________________________________________________________
my_obj_beamprofile_e13	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e13))
my_obj_beamprofile_e13	:= $(my_obj_beamprofile_e13)
my_lib_beamprofile_e13 := libmybeamprofile_e13.so
$(eval $(call make-lib,$(my_lib_beamprofile_e13),$(my_obj_beamprofile_e13)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e13),$(my_lib_beamprofile_e13)))

#_______________________________________________________________________________
my_obj_beamprofile_e07	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e07))
my_obj_beamprofile_e07	:= $(my_obj_beamprofile_e07)
my_lib_beamprofile_e07 := libmybeamprofile_e07.so
$(eval $(call make-lib,$(my_lib_beamprofile_e07),$(my_obj_beamprofile_e07)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e07),$(my_lib_beamprofile_e07)))

#_______________________________________________________________________________
my_obj_beamprofile_e05	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e05))
my_obj_beamprofile_e05	:= $(my_obj_beamprofile_e05)
my_lib_beamprofile_e05 := libmybeamprofile_e05.so
$(eval $(call make-lib,$(my_lib_beamprofile_e05),$(my_obj_beamprofile_e05)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e05),$(my_lib_beamprofile_e05)))

#_______________________________________________________________________________
my_obj_beamprofile_e03	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e03))
my_obj_beamprofile_e03	:= $(my_obj_beamprofile_e03)
my_lib_beamprofile_e03 := libmybeamprofile_e03.so
$(eval $(call make-lib,$(my_lib_beamprofile_e03),$(my_obj_beamprofile_e03)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e03),$(my_lib_beamprofile_e03)))

#_______________________________________________________________________________
my_obj_beamprofile_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e40))
my_obj_beamprofile_e40	:= $(my_obj_beamprofile_e40)
my_lib_beamprofile_e40 := libmybeamprofile_e40.so
$(eval $(call make-lib,$(my_lib_beamprofile_e40),$(my_obj_beamprofile_e40)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e40),$(my_lib_beamprofile_e40)))

#_______________________________________________________________________________
my_obj_beamprofile_e42	:= $(addprefix $(my_dir)/src/,$(my_obj_beamprofile_e42))
my_obj_beamprofile_e42	:= $(my_obj_beamprofile_e42)
my_lib_beamprofile_e42 := libmybeamprofile_e42.so
$(eval $(call make-lib,$(my_lib_beamprofile_e42),$(my_obj_beamprofile_e42)))
$(eval $(call make-gui-target,$(my_tgt_beamprofile_e42),$(my_lib_beamprofile_e42)))

#_______________________________________________________________________________
my_obj_emc_ssd_monitor	:= $(addprefix $(my_dir)/src/,$(my_obj_emc_ssd_monitor))
my_lib_emc_ssd_monitor	:= libmyemc_ssd_monitor.so
$(eval $(call make-lib,$(my_lib_emc_ssd_monitor),$(my_obj_emc_ssd_monitor)))
$(eval $(call make-nogui-target,$(my_tgt_emc_ssd_monitor),$(my_lib_emc_ssd_monitor)))

#_______________________________________________________________________________
my_obj_scaler_e13 := $(addprefix $(my_dir)/src/,$(my_obj_scaler_e13))
my_lib_scaler_e13 := libmyscaler_e13.so
$(eval $(call make-lib,$(my_lib_scaler_e13),$(my_obj_scaler_e13)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e13),$(my_lib_scaler_e13)))

#_______________________________________________________________________________
my_obj_scaler_e0705	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_e0705))
my_lib_scaler_e0705	:= libmyscaler_e0705.so
$(eval $(call make-lib,$(my_lib_scaler_e0705),$(my_obj_scaler_e0705)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e0705),$(my_lib_scaler_e0705)))

#_______________________________________________________________________________
my_obj_scaler_e07	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_e07))
my_lib_scaler_e07	:= libmyscaler_e07.so
$(eval $(call make-lib,$(my_lib_scaler_e07),$(my_obj_scaler_e07)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e07),$(my_lib_scaler_e07)))

#_______________________________________________________________________________
my_obj_scaler_e40	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_e40))
my_lib_scaler_e40	:= libmyscaler_e40.so
$(eval $(call make-lib,$(my_lib_scaler_e40),$(my_obj_scaler_e40)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e40),$(my_lib_scaler_e40)))

#_______________________________________________________________________________
my_obj_scaler_e03	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_e03))
my_lib_scaler_e03	:= libmyscaler_e03.so
$(eval $(call make-lib,$(my_lib_scaler_e03),$(my_obj_scaler_e03)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e03),$(my_lib_scaler_e03)))

#_______________________________________________________________________________
my_obj_scaler_e42	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_e42))
my_lib_scaler_e42	:= libmyscaler_e42.so
$(eval $(call make-lib,$(my_lib_scaler_e42),$(my_obj_scaler_e42)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_e42),$(my_lib_scaler_e42)))

#_______________________________________________________________________________
my_obj_scaler_sch	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_sch))
my_lib_scaler_sch	:= libmyscaler_sch.so
$(eval $(call make-lib,$(my_lib_scaler_sch),$(my_obj_scaler_sch)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_sch),$(my_lib_scaler_sch)))

#_______________________________________________________________________________
my_obj_scaler_daq	:= $(addprefix $(my_dir)/src/,$(my_obj_scaler_daq))
my_lib_scaler_daq	:= libmyscaler_daq.so
$(eval $(call make-lib,$(my_lib_scaler_daq),$(my_obj_scaler_daq)))
$(eval $(call make-nogui-target,$(my_tgt_scaler_daq),$(my_lib_scaler_daq)))

#_______________________________________________________________________________
my_obj_hbjscaler	:= $(addprefix $(my_dir)/src/,$(my_obj_hbjscaler))
my_lib_hbjscaler	:= libmyhbjscaler.so
$(eval $(call make-lib,$(my_lib_hbjscaler),$(my_obj_hbjscaler)))
$(eval $(call make-nogui-target,$(my_tgt_hbjscaler),$(my_lib_hbjscaler)))

#_______________________________________________________________________________
my_obj_hbj_ana	:= $(addprefix $(my_dir)/src/,$(my_obj_hbj_ana))
my_obj_hbj_ana	:= $(my_obj_hbj_ana) \
		  $(my_dir)/dict/GuiPs_Dict.o
my_lib_hbj_ana	:= libmyhbj_ana.so
$(eval $(call make-lib,$(my_lib_hbj_ana),$(my_obj_hbj_ana)))
$(eval $(call make-gui-target,$(my_tgt_hbj_ana),$(my_lib_hbj_ana)))

#_______________________________________________________________________________
my_obj_pwo	:= $(addprefix $(my_dir)/src/,$(my_obj_pwo))
my_obj_pwo	:= $(my_obj_pwo)
my_lib_pwo	:= libmypwo.so
$(eval $(call make-lib,$(my_lib_pwo),$(my_obj_pwo)))
$(eval $(call make-gui-target,$(my_tgt_pwo),$(my_lib_pwo)))


#_______________________________________________________________________________
my_obj_ktune_y2020      := $(addprefix $(my_dir)/src/,$(my_obj_ktune_y2020))
my_obj_ktune_y2020      := $(my_obj_ktune_y2020) \
		        $(my_dir)/dict/GuiPs_Dict.o
my_lib_ktune_y2020      := libmyktune_y2020.so
$(eval $(call make-lib,$(my_lib_ktune_y2020),$(my_obj_ktune_y2020)))
$(eval $(call make-gui-target,$(my_tgt_ktune_y2020),$(my_lib_ktune_y2020)))
