#!/bin/sh
##
#  shell script for online/semi online analyzer
##

. $(dirname $(readlink -f $0))/setebhost

dis_port=8901
rec_port=8902

#port=$rec_port
port=$dis_port

ana_dir=$(dirname $(readlink -f $0))/..
bin_dir=$ana_dir/bin

##### execute file
exe_file=$bin_dir/event_display

##### data directory
data_dir=$ana_dir/data

##### configure file
conf_file=/param/conf/analyzer_evdisp.conf

#######################################################################
if [ ! -f $exe_file ]; then
    echo "#E [$(basename $0)] no such file: $exe_file"
    exit
fi
if [ ! -f $conf_file ]; then
    echo "#E [$(basename $0)] no such file: $conf_file"
    exit
fi

if [ $# = 0 ]; then
    $exe_file $conf_file ${ebhost}:$port
    exit
fi

data_file=$data_dir/run$1.dat
if [ ! -f $data_file ]; then
    data_file=$data_dir/run$1.dat.gz
    if [ ! -f $data_file ]; then
	echo "#E [$(basename $0)] no such file: $data_file"
	exit
    fi
fi

if [ $# = 1 ]; then
    $exe_file $conf_file $data_file
elif [ $# = 2 ]; then
    $exe_file $conf_file $data_file $2
else
    echo "#D Usage: $(basename $0) [run number]"
fi
