#!/bin/sh

ebhost=eb0

dis_port=8901
rec_port=8902

#port=$rec_port
port=$dis_port

ana_dir=$(dirname $(readlink -f $0))/..
bin_dir=$ana_dir/bin

##### execute file
exe_file=$bin_dir/scaler_e0705

##### data directory
data_dir=/data1/bench_e07-05

##### configure file
conf_file=/param/conf/analyzer_scaler_e0705.conf

#######################################################################
if [ ! -f $exe_file ]; then
    echo "#E [$(basename $0)] no such file: $exe_file"
    exit
fi
if [ ! -f $conf_file ]; then
    echo "#E [$(basename $0)] no such file: $conf_file"
    exit
fi

if [ $# = 0 ]; then
    $exe_file $conf_file ${ebhost}:$port

elif [ $# = 1 ]; then
    data_file=$data_dir/run$1.dat.gz
    if [ ! -f $data_file ]; then
	echo "#E [$(basename $0)] no such file: $data_file"
	exit
    fi

    $exe_file $conf_file $data_file
    
else
    echo "#D Usage: $(basename $0) [run number]"
fi
