subdir := main analyzer

#_______________________________________________________________________________
all:
	@ for dir in $(subdir); \
	do \
		cd $$dir; \
		$(MAKE); \
		cd ..; \
	done;

#_______________________________________________________________________________
show:
	@ echo "Package List = $(subdir)"
	@ for dir in $(subdir); \
	do \
		cd $$dir; \
		$(MAKE) show; \
		cd ..; \
	done;

#_______________________________________________________________________________
clean::
	@ rm -fv *~
	@ for dir in $(subdir); \
	do \
		cd $$dir; \
		$(MAKE) clean; \
		cd ..; \
	done;

#_______________________________________________________________________________
distclean::
	@ rm -fv ../lib/* ../include/* ../bin/*
	@ for dir in $(subdir); \
	do \
		cd $$dir; \
		$(MAKE) distclean; \
		cd ..; \
	done;
